defaults: &defaults
  db_adapter: postgresql
  db_encoding: unicode
  db_pool: 5
  db_host: localhost
  db_port: 3306
  db_username: postgres
  db_password: postgres
  db_name: app_database
  app_base_url: 'http://localhost:3001'

local_dev:
  <<: *defaults

ci:
  <<: *defaults
  db_host: database.ci
  app_base_url: 'http://app-proxy.ci'

qa:
  <<: *defaults
  db_host: database.qa
  app_base_url: 'http://app-proxy.qa'

showcase:
  <<: *defaults
  db_host: database.showcase
  app_base_url: 'http://app-proxy.showcase'

uat:
  <<: *defaults
  db_host: database.uat
  app_base_url: 'http://app-proxy.uat'
